import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateUserTable1747055429609 implements MigrationInterface {
    name = 'CreateUserTable1747055429609'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "cultural_content" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(100) NOT NULL, "description" text NOT NULL, "category" character varying(50) NOT NULL DEFAULT 'general', "content" text NOT NULL, "mediaUrls" text array, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_58ca68ae2b6b29497ab1b14a313" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evaluation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "score" integer NOT NULL, "answers" jsonb, "attemptsCount" integer NOT NULL DEFAULT '0', "averageScore" double precision NOT NULL DEFAULT '0', "timeSpentSeconds" integer NOT NULL DEFAULT '0', "progressMetrics" jsonb, "feedback" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "culturalContentId" uuid, CONSTRAINT "PK_b72edd439b9db736f55b584fa54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "revoked_token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_572b4c3824a800e4341ee43fcee" UNIQUE ("token"), CONSTRAINT "PK_bf300a6daf55d675aba672ba1f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activity_type_enum" AS ENUM('reading', 'writing', 'listening', 'speaking', 'cultural', 'interactive')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_difficulty_enum" AS ENUM('beginner', 'intermediate', 'advanced', 'expert')`);
        await queryRunner.query(`CREATE TABLE "activity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "type" "public"."activity_type_enum" NOT NULL DEFAULT 'interactive', "difficulty" "public"."activity_difficulty_enum" NOT NULL DEFAULT 'beginner', "content" json NOT NULL, "points" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_24625a1d6b1b089c8ae206fe467" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "points" integer NOT NULL DEFAULT '0', "level" integer NOT NULL DEFAULT '1', "streak" integer NOT NULL DEFAULT '0', "lastActivity" TIMESTAMP, "settings" json NOT NULL DEFAULT '{}', "preferences" json NOT NULL DEFAULT '{}', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."leaderboards_type_enum" AS ENUM('daily', 'weekly', 'monthly', 'all_time')`);
        await queryRunner.query(`CREATE TYPE "public"."leaderboards_category_enum" AS ENUM('points', 'lessons_completed', 'exercises_completed', 'perfect_scores', 'learning_streak', 'cultural_contributions')`);
        await queryRunner.query(`CREATE TABLE "leaderboards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."leaderboards_type_enum" NOT NULL DEFAULT 'daily', "category" "public"."leaderboards_category_enum" NOT NULL DEFAULT 'points', "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "rankings" jsonb NOT NULL, "rewards" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "lastUpdated" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_190f95e31621935228328d6c20a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "base_achievement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "iconUrl" character varying, CONSTRAINT "PK_73d09fbdfdcb105e7a60469815c" PRIMARY KEY ("id")); COMMENT ON COLUMN "base_achievement"."iconUrl" IS 'Icon or image URL'`);
        await queryRunner.query(`CREATE TABLE "badge" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text NOT NULL, "category" character varying(50) NOT NULL, "tier" character varying(50) NOT NULL, "requiredPoints" integer NOT NULL, "iconUrl" character varying(255), "requirements" jsonb NOT NULL DEFAULT '{}', "isSpecial" boolean NOT NULL DEFAULT false, "expirationDate" date, "timesAwarded" integer NOT NULL DEFAULT '0', "benefits" jsonb NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76b7011c864d4521a14a5196c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "iconUrl" character varying, "criteria" character varying NOT NULL, "requirement" integer NOT NULL DEFAULT '0', "bonusPoints" integer NOT NULL DEFAULT '0', "isSecret" boolean NOT NULL DEFAULT false, "isSpecial" boolean NOT NULL DEFAULT false, "badgeId" uuid, CONSTRAINT "PK_1bc19c37c6249f70186f318d71d" PRIMARY KEY ("id")); COMMENT ON COLUMN "achievements"."iconUrl" IS 'Icon or image URL'; COMMENT ON COLUMN "achievements"."criteria" IS 'Criteria needed to complete, e.g., points, lessons completed'`);
        await queryRunner.query(`CREATE TYPE "public"."user_achievements_achievementtype_enum" AS ENUM('GENERAL', 'CULTURAL')`);
        await queryRunner.query(`CREATE TYPE "public"."user_achievements_status_enum" AS ENUM('IN_PROGRESS', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "user_achievements" ("userId" uuid NOT NULL, "achievementId" uuid NOT NULL, "achievementType" "public"."user_achievements_achievementtype_enum" NOT NULL DEFAULT 'GENERAL', "status" "public"."user_achievements_status_enum" NOT NULL DEFAULT 'IN_PROGRESS', "progress" json, "completedAt" TIMESTAMP, "dateAwarded" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1acd69cf91b1e353634c152dd7" PRIMARY KEY ("userId", "achievementId"))`);
        await queryRunner.query(`CREATE TYPE "public"."reward_type_enum" AS ENUM('badge', 'points', 'achievement', 'cultural', 'experience', 'content', 'discount', 'exclusive_content', 'customization')`);
        await queryRunner.query(`CREATE TABLE "reward" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "type" "public"."reward_type_enum" NOT NULL, "pointsCost" integer, "imageUrl" text, CONSTRAINT "PK_a90ea606c229e380fb341838036" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_rewards" ("userId" uuid NOT NULL, "rewardId" uuid NOT NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "metadata" json, "consumedAt" TIMESTAMP, "expiresAt" TIMESTAMP, "dateAwarded" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8162d48f7242ea2e1410f5a763d" PRIMARY KEY ("userId", "rewardId"))`);
        await queryRunner.query(`CREATE TABLE "multimedia" ("id" SERIAL NOT NULL, "fileName" character varying NOT NULL, "filePath" character varying NOT NULL, "fileType" character varying NOT NULL, "mimeType" character varying, "size" integer, "userId" character varying NOT NULL, "lessonId" uuid, CONSTRAINT "PK_8de2f47ce83e221b35e05e52d0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "topics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "order" integer NOT NULL DEFAULT '1', "isLocked" boolean NOT NULL DEFAULT false, "requiredPoints" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "unityId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e4aa99a3fa60ec3a37d1fc4e853" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "module" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_0e20d657f968b051e674fbe3117" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "order" integer NOT NULL DEFAULT '1', "isLocked" boolean NOT NULL DEFAULT false, "requiredPoints" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "userId" uuid NOT NULL, "moduleId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_42e005e82cfebf8cedfccd1a8f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "order" integer NOT NULL DEFAULT '1', "isLocked" boolean NOT NULL DEFAULT false, "isCompleted" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "requiredPoints" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "unityId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0ef25918f0237e68696dee455bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exercises" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying NOT NULL, "type" character varying NOT NULL, "content" json NOT NULL, "difficulty" character varying NOT NULL, "points" integer NOT NULL, "timeLimit" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "topicId" uuid NOT NULL, "tags" text, "timesCompleted" integer NOT NULL DEFAULT '0', "averageScore" double precision NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "lessonId" uuid, "progressId" uuid, CONSTRAINT "PK_c4c46f5fa89a58ba7c2d894e3c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "score" integer NOT NULL DEFAULT '0', "isCompleted" boolean NOT NULL DEFAULT false, "answers" json, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "exerciseId" uuid, CONSTRAINT "PK_79abdfd87a688f9de756a162b6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "statistics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "categoryMetrics" jsonb NOT NULL DEFAULT '{}', "strengthAreas" jsonb NOT NULL DEFAULT '[]', "improvementAreas" jsonb NOT NULL DEFAULT '[]', "learningMetrics" jsonb NOT NULL, "weeklyProgress" jsonb NOT NULL DEFAULT '[]', "monthlyProgress" jsonb NOT NULL DEFAULT '[]', "periodicProgress" jsonb NOT NULL DEFAULT '[]', "achievementStats" jsonb NOT NULL, "badgeStats" jsonb NOT NULL, "learningPath" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_c9989a8e8506743633ba5e0aed" UNIQUE ("userId"), CONSTRAINT "PK_c3769cca342381fa827a0f246a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'student', 'teacher', 'admin', 'moderator')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'pending', 'banned')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "languages" text array NOT NULL, "preferences" json NOT NULL, "culturalPoints" integer NOT NULL DEFAULT '0', "level" integer NOT NULL DEFAULT '1', "points" integer NOT NULL DEFAULT '0', "gameStats" json, "resetPasswordToken" character varying, "resetPasswordExpires" TIMESTAMP, "lastLoginAt" TIMESTAMP, "isEmailVerified" boolean NOT NULL DEFAULT false, "dateOfBirth" date, "country" character varying, "city" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "webhook_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" text NOT NULL, "events" text NOT NULL, "secret" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "lastTriggeredAt" TIMESTAMP, "failureCount" integer NOT NULL DEFAULT '0', "metadata" jsonb, CONSTRAINT "PK_bf631ae77d39849d599817fb6f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vocabulary" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "word" character varying NOT NULL, "translation" character varying NOT NULL, "description" character varying, "example" character varying, "audioUrl" character varying, "imageUrl" character varying, "points" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "topicId" uuid, CONSTRAINT "PK_65dbd74f76cee79778299a2a21b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tags_type_enum" AS ENUM('difficulty', 'topic', 'skill', 'cultural', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."tags_color_enum" AS ENUM('red', 'blue', 'green', 'yellow', 'purple', 'orange', 'pink', 'gray', 'brown')`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "type" "public"."tags_type_enum" NOT NULL DEFAULT 'custom', "color" "public"."tags_color_enum" NOT NULL DEFAULT 'gray', "description" text, "parentId" uuid, "metadata" jsonb, "usageCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('achievement_unlocked', 'reward_earned', 'level_up', 'streak_milestone', 'cultural_content', 'system', 'new_message', 'mission_completed', 'collaboration_update')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('unread', 'read', 'archived')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'medium', "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'unread', "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "metadata" json, "isActive" boolean NOT NULL DEFAULT true, "isPush" boolean NOT NULL DEFAULT false, "isEmail" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rewards_type_enum" AS ENUM('badge', 'points', 'achievement', 'cultural', 'experience', 'content', 'discount', 'exclusive_content', 'customization')`);
        await queryRunner.query(`CREATE TYPE "public"."rewards_trigger_enum" AS ENUM('level_up', 'lesson_completion', 'exercise_completion')`);
        await queryRunner.query(`CREATE TABLE "rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "type" "public"."rewards_type_enum" NOT NULL DEFAULT 'badge', "trigger" "public"."rewards_trigger_enum" NOT NULL DEFAULT 'level_up', "pointsCost" integer NOT NULL DEFAULT '0', "criteria" json, "conditions" json, "rewardValue" json, "isLimited" boolean, "limitedQuantity" integer, "startDate" TIMESTAMP, "endDate" TIMESTAMP, "timesAwarded" integer NOT NULL DEFAULT '0', "points" integer NOT NULL DEFAULT '0', "isSecret" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "expirationDays" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3d947441a48debeb9b7366f8b8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gamification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "points" integer NOT NULL DEFAULT '0', "stats" json NOT NULL DEFAULT '{"lessonsCompleted":0,"exercisesCompleted":0,"perfectScores":0,"culturalContributions":0}', "milestones" jsonb, "levelHistory" jsonb NOT NULL DEFAULT '[]', "activityLog" jsonb NOT NULL DEFAULT '[]', "bonuses" jsonb NOT NULL DEFAULT '[]', "recentActivities" json NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "level" integer NOT NULL DEFAULT '1', "experience" double precision NOT NULL DEFAULT '0', "nextLevelExperience" double precision NOT NULL DEFAULT '100', "culturalAchievements" json NOT NULL DEFAULT '[]', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e24e36fa415495cb1eeeb48c7f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."special_events_type_enum" AS ENUM('festival', 'ceremonia', 'encuentro', 'taller', 'competicion', 'exposicion')`);
        await queryRunner.query(`CREATE TABLE "special_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "type" "public"."special_events_type_enum" NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "rewards" json NOT NULL, "requirements" json NOT NULL, "culturalElements" json NOT NULL, "isActive" boolean NOT NULL DEFAULT false, "participants" json NOT NULL DEFAULT '[]', "seasonId" uuid, CONSTRAINT "PK_872fcb3effc72ddc6a289a6059b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."season_type_enum" AS ENUM('betscnate', 'jajan', 'bengbe_betsa', 'anteuan', 'flor_de_mayo', 'dia_grande')`);
        await queryRunner.query(`CREATE TABLE "season" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."season_type_enum" NOT NULL DEFAULT 'betscnate', "name" character varying NOT NULL, "description" character varying NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "culturalElements" json NOT NULL, "rewards" json NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ac0d081dbdb7ab02d166bcda9f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."missions_type_enum" AS ENUM('COMPLETE_LESSONS', 'PRACTICE_EXERCISES', 'EARN_POINTS', 'MAINTAIN_STREAK', 'CULTURAL_CONTENT', 'COMMUNITY_INTERACTION', 'VOCABULARY', 'PERSONALIZED', 'PROGRESS_BASED', 'SEASONAL', 'COMMUNITY', 'LEARN_VOCABULARY', 'PARTICIPATE_FORUM', 'COMMUNITY_ENGAGEMENT', 'CONTENT_CREATION', 'PERFECT_SCORES')`);
        await queryRunner.query(`CREATE TYPE "public"."missions_frequency_enum" AS ENUM('diaria', 'semanal', 'mensual', 'temporada', 'contribucion', 'unica')`);
        await queryRunner.query(`CREATE TABLE "missions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying NOT NULL, "type" "public"."missions_type_enum" NOT NULL, "criteria" jsonb, "frequency" "public"."missions_frequency_enum" NOT NULL, "targetValue" integer NOT NULL, "rewardPoints" integer NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "completedBy" jsonb NOT NULL DEFAULT '[]', "bonusConditions" jsonb, "seasonId" uuid, "rewardBadgeId" uuid, CONSTRAINT "PK_787aebb1ac5923c9904043c6309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_missions" ("id" SERIAL NOT NULL, "userId" uuid, "missionId" uuid, CONSTRAINT "PK_252d92542f9926e799c0161ac46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_level" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL DEFAULT '1', "experience" integer NOT NULL DEFAULT '0', "points" integer NOT NULL DEFAULT '0', "experienceToNextLevel" integer NOT NULL DEFAULT '0', "consistencyStreak" jsonb NOT NULL DEFAULT '{"current":0,"longest":0,"lastActivityDate":null}', "streakHistory" jsonb NOT NULL DEFAULT '[]', "levelHistory" jsonb NOT NULL DEFAULT '[]', "activityLog" jsonb NOT NULL DEFAULT '[]', "bonuses" jsonb NOT NULL DEFAULT '[]', "lessonsCompleted" integer NOT NULL DEFAULT '0', "exercisesCompleted" integer NOT NULL DEFAULT '0', "perfectScores" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "REL_d5fd95368e5ce39ff4baa96446" UNIQUE ("userId"), CONSTRAINT "PK_d33d938ab8244a12eccac00edd2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_badges" ("userId" uuid NOT NULL, "badgeId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76e9ac35f4d56715c688a345fe6" PRIMARY KEY ("userId", "badgeId"))`);
        await queryRunner.query(`CREATE TABLE "streaks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "currentStreak" integer NOT NULL DEFAULT '0', "longestStreak" integer NOT NULL DEFAULT '0', "lastActivityDate" TIMESTAMP, "graceDate" TIMESTAMP, "usedGracePeriod" boolean NOT NULL DEFAULT false, "streakHistory" jsonb NOT NULL DEFAULT '[]', "currentMultiplier" numeric NOT NULL DEFAULT '1', CONSTRAINT "PK_52547016a1a6409f6e5287ed859" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mentors_level_enum" AS ENUM('aprendiz', 'intermedio', 'avanzado', 'maestro', 'sabedor', 'basico')`);
        await queryRunner.query(`CREATE TABLE "mentors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "level" "public"."mentors_level_enum" NOT NULL DEFAULT 'aprendiz', "stats" json NOT NULL, "availability" json NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_67a614446eab992e4d0580afebf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mentor_specializations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL DEFAULT 'DANZA', "level" integer NOT NULL, "description" text NOT NULL, "certifications" json NOT NULL, "endorsements" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "mentorId" uuid, CONSTRAINT "PK_3dd4e53d32865219da3421584bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mentorship_relations_type_enum" AS ENUM('ESTUDIANTE_ESTUDIANTE', 'DOCENTE_ESTUDIANTE')`);
        await queryRunner.query(`CREATE TABLE "mentorship_relations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "studentId" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'PENDING', "type" "public"."mentorship_relations_type_enum" NOT NULL DEFAULT 'DOCENTE_ESTUDIANTE', "focusArea" character varying NOT NULL, "goals" json NOT NULL, "sessions" json NOT NULL, "progress" json NOT NULL, "startDate" TIMESTAMP, "endDate" TIMESTAMP, "completionCertificate" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "mentorId" uuid, CONSTRAINT "PK_6ecbda822c4359789bc0ccac0d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mission_templates_type_enum" AS ENUM('COMPLETE_LESSONS', 'PRACTICE_EXERCISES', 'EARN_POINTS', 'MAINTAIN_STREAK', 'CULTURAL_CONTENT', 'COMMUNITY_INTERACTION', 'VOCABULARY', 'PERSONALIZED', 'PROGRESS_BASED', 'SEASONAL', 'COMMUNITY', 'LEARN_VOCABULARY', 'PARTICIPATE_FORUM', 'COMMUNITY_ENGAGEMENT', 'CONTENT_CREATION', 'PERFECT_SCORES')`);
        await queryRunner.query(`CREATE TYPE "public"."mission_templates_frequency_enum" AS ENUM('diaria', 'semanal', 'mensual', 'temporada', 'contribucion', 'unica')`);
        await queryRunner.query(`CREATE TABLE "mission_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "type" "public"."mission_templates_type_enum" NOT NULL, "frequency" "public"."mission_templates_frequency_enum" NOT NULL, "category" character varying, "tags" character varying, "conditions" json, "rewards" json, "startDate" date, "endDate" date, "isActive" boolean NOT NULL DEFAULT true, "minLevel" integer NOT NULL DEFAULT '1', "maxLevel" integer NOT NULL DEFAULT '0', "baseTargetValue" double precision NOT NULL DEFAULT '1', "baseRewardPoints" double precision NOT NULL DEFAULT '1', "bonusConditions" jsonb, "requirements" jsonb, "difficultyScaling" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9df1a47e0c0eee2716157f76b64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cultural_achievements_category_enum" AS ENUM('lengua', 'danza', 'musica', 'artesania', 'historia', 'tradicion', 'gastronomia', 'medicina', 'rituales', 'mitos_leyendas')`);
        await queryRunner.query(`CREATE TYPE "public"."cultural_achievements_type_enum" AS ENUM('aprendizaje_cultural', 'exploracion_contenido', 'participacion_evento', 'creacion_contenido', 'contribucion_cultural', 'aprendizaje_lengua', 'dominio_cultural')`);
        await queryRunner.query(`CREATE TYPE "public"."cultural_achievements_tier_enum" AS ENUM('bronce', 'plata', 'oro', 'platino', 'ancestral')`);
        await queryRunner.query(`CREATE TABLE "cultural_achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text NOT NULL, "iconUrl" character varying, "category" "public"."cultural_achievements_category_enum" NOT NULL, "type" "public"."cultural_achievements_type_enum" NOT NULL DEFAULT 'contribucion_cultural', "tier" "public"."cultural_achievements_tier_enum" NOT NULL, "requirements" json NOT NULL, "pointsReward" integer NOT NULL, "expirationDays" integer, "additionalRewards" json, "isActive" boolean NOT NULL DEFAULT true, "isSecret" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_53b55072c9cc68657fc7e68399f" PRIMARY KEY ("id")); COMMENT ON COLUMN "cultural_achievements"."iconUrl" IS 'Icon or image URL'`);
        await queryRunner.query(`CREATE TYPE "public"."collaboration_rewards_type_enum" AS ENUM('CONTENIDO_CREACION', 'CONTENIDO_REVISION', 'CONTRIBUCION_CULTURAL', 'CONTENIDO_TRADUCCION', 'AYUDA_COMUNITARIA', 'REPORTE_ERRORES')`);
        await queryRunner.query(`CREATE TABLE "collaboration_rewards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."collaboration_rewards_type_enum" NOT NULL, "title" character varying NOT NULL, "description" character varying NOT NULL, "basePoints" integer NOT NULL, "qualityMultipliers" jsonb NOT NULL, "history" jsonb NOT NULL, "streakBonuses" jsonb NOT NULL, "specialBadgeId" uuid, CONSTRAINT "REL_80cb295d4e4e8a0feb787d0846" UNIQUE ("specialBadgeId"), CONSTRAINT "PK_62e3cb5387f663c712aae04b2e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "achievement_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "progress" json NOT NULL, "percentageCompleted" double precision NOT NULL, "isCompleted" boolean NOT NULL DEFAULT false, "completedAt" TIMESTAMP, "milestones" json, "rewardsCollected" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "achievementId" uuid, CONSTRAINT "PK_901cc379a8dbe909f3d617c0da1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "content" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "description" text, "type" character varying(50) NOT NULL, "content" jsonb, "unity_id" uuid NOT NULL, "topic_id" uuid NOT NULL, "order" integer, "categories" text, "tags" text, CONSTRAINT "PK_6a2083913f3647b44f205204e36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."content_versions_status_enum" AS ENUM('active', 'inactive', 'draft', 'review', 'published')`);
        await queryRunner.query(`CREATE TYPE "public"."content_versions_changetype_enum" AS ENUM('CREATION', 'MODIFICATION', 'DELETION', 'MERGE', 'REVERT')`);
        await queryRunner.query(`CREATE TABLE "content_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contentId" integer NOT NULL, "contentData" jsonb NOT NULL, "majorVersion" integer NOT NULL, "minorVersion" integer NOT NULL, "patchVersion" integer NOT NULL, "status" "public"."content_versions_status_enum" NOT NULL, "changeType" "public"."content_versions_changetype_enum" NOT NULL, "metadata" jsonb, "validationStatus" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_77046b137eb8001947fc332e594" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" character varying NOT NULL, "author" character varying NOT NULL, "parentId" uuid, "versionId" uuid NOT NULL, "mentions" text, "attachments" text, "metadata" jsonb, "isResolved" boolean NOT NULL DEFAULT false, "resolvedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "resolvedAt" TIMESTAMP, "tags" text, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."content_validation_contenttype_enum" AS ENUM('WORD', 'PHRASE', 'SENTENCE', 'DIALOGUE', 'CULTURAL_CONTENT')`);
        await queryRunner.query(`CREATE TYPE "public"."content_validation_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVIEW')`);
        await queryRunner.query(`CREATE TABLE "content_validation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contentId" character varying NOT NULL, "contentType" "public"."content_validation_contenttype_enum" NOT NULL, "originalContent" text NOT NULL, "translatedContent" text, "status" "public"."content_validation_status_enum" NOT NULL DEFAULT 'PENDING', "criteria" jsonb NOT NULL, "feedback" jsonb NOT NULL DEFAULT '[]', "validatedBy" text array NOT NULL DEFAULT '{}', "submittedBy" character varying NOT NULL, "submissionDate" TIMESTAMP NOT NULL DEFAULT now(), "lastModifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "validationScore" double precision NOT NULL DEFAULT '0', "communityVotes" jsonb NOT NULL, "dialectVariation" text, "culturalContext" text, "usageExamples" text array, "audioReference" text, "relatedContent" text array, "metadata" jsonb NOT NULL DEFAULT '{}', "isUrgent" boolean NOT NULL DEFAULT false, "tags" text array NOT NULL DEFAULT '{}', CONSTRAINT "PK_0a5b2a2dc89d183be9b09d1c900" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "description" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gamification_achievements_achievements" ("gamificationId" uuid NOT NULL, "achievementsId" uuid NOT NULL, CONSTRAINT "PK_84cfb185158d8157c43801267e8" PRIMARY KEY ("gamificationId", "achievementsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ea46f6118e982baae585fa28a6" ON "gamification_achievements_achievements" ("gamificationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dac3e2f218b828cfeabc4b274b" ON "gamification_achievements_achievements" ("achievementsId") `);
        await queryRunner.query(`CREATE TABLE "gamification_badges_badge" ("gamificationId" uuid NOT NULL, "badgeId" uuid NOT NULL, CONSTRAINT "PK_c0c788d39bb0cea80fb1ece0eb0" PRIMARY KEY ("gamificationId", "badgeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb9fb4bce626c7391ee29e4afa" ON "gamification_badges_badge" ("gamificationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_60a494139c28edaff1797ad1b5" ON "gamification_badges_badge" ("badgeId") `);
        await queryRunner.query(`CREATE TABLE "gamification_active_missions_missions" ("gamificationId" uuid NOT NULL, "missionsId" uuid NOT NULL, CONSTRAINT "PK_8a3bc5662b5ad155ca6235022c9" PRIMARY KEY ("gamificationId", "missionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c868524a6ca0aff77eb58c3ae" ON "gamification_active_missions_missions" ("gamificationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf067ab5b71aafeb41c8aa81d9" ON "gamification_active_missions_missions" ("missionsId") `);
        await queryRunner.query(`CREATE TABLE "content_multimedia" ("content_id" integer NOT NULL, "multimedia_id" integer NOT NULL, CONSTRAINT "PK_e47b10b122fdb42bea40b7e3659" PRIMARY KEY ("content_id", "multimedia_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bc7887b608f489d149b88549a8" ON "content_multimedia" ("content_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb81782a60801a96a1b97da930" ON "content_multimedia" ("multimedia_id") `);
        await queryRunner.query(`ALTER TABLE "evaluation" ADD CONSTRAINT "FK_df167b6625e01d4e26b08b02ba2" FOREIGN KEY ("culturalContentId") REFERENCES "cultural_content"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity" ADD CONSTRAINT "FK_3571467bcbe021f66e2bdce96ea" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_3aa23c0a6d107393e8b40e3e2a6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leaderboards" ADD CONSTRAINT "FK_0b345cd9c25536011d892d0939c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievements" ADD CONSTRAINT "FK_75e5dd5e08a7ae1f1b24332ef12" FOREIGN KEY ("badgeId") REFERENCES "badge"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievements" ADD CONSTRAINT "FK_3ac6bc9da3e8a56f3f7082012dd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_achievements" ADD CONSTRAINT "FK_6a5a5816f54d0044ba5f3dc2b74" FOREIGN KEY ("achievementId") REFERENCES "achievements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_rewards" ADD CONSTRAINT "FK_d538de4678c82491e5a8a8a5834" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_rewards" ADD CONSTRAINT "FK_d2904b4fa623c996161687e47d1" FOREIGN KEY ("rewardId") REFERENCES "reward"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "multimedia" ADD CONSTRAINT "FK_be02075eb7a71c44dfc3dbe5651" FOREIGN KEY ("lessonId") REFERENCES "lesson"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "topics" ADD CONSTRAINT "FK_5d52d2f497534a9e39820d2d817" FOREIGN KEY ("unityId") REFERENCES "unities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unities" ADD CONSTRAINT "FK_3febc6c71f0413485f16cbd1c9b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unities" ADD CONSTRAINT "FK_a34b5225d21eb0609ff7ee71f68" FOREIGN KEY ("moduleId") REFERENCES "module"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson" ADD CONSTRAINT "FK_f52253c85fe9f56320420603d01" FOREIGN KEY ("unityId") REFERENCES "unities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_947b3be6e0895a3a12ad355ab16" FOREIGN KEY ("topicId") REFERENCES "topics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_c7a7b90ae6ce91a6d8bcf09b8b6" FOREIGN KEY ("lessonId") REFERENCES "lesson"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_98668b9e9d6495aef985bf0ba33" FOREIGN KEY ("progressId") REFERENCES "progress"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress" ADD CONSTRAINT "FK_0366c96237f98ea1c8ba6e1ec35" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress" ADD CONSTRAINT "FK_36b66733d026a365fb6e6dd63ae" FOREIGN KEY ("exerciseId") REFERENCES "exercises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "statistics" ADD CONSTRAINT "FK_c9989a8e8506743633ba5e0aed0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary" ADD CONSTRAINT "FK_5a3aa0bd439dc502c591a53b591" FOREIGN KEY ("topicId") REFERENCES "topics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tags" ADD CONSTRAINT "FK_9f9590cc11561f1f48ff034ef99" FOREIGN KEY ("parentId") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gamification" ADD CONSTRAINT "FK_0ab5141fb59488a7f83cf347fed" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "special_events" ADD CONSTRAINT "FK_465c2111241435bcd1706474e38" FOREIGN KEY ("seasonId") REFERENCES "season"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "missions" ADD CONSTRAINT "FK_e6378fac08e39332e726de694dd" FOREIGN KEY ("seasonId") REFERENCES "season"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "missions" ADD CONSTRAINT "FK_5debe2687492eacccc1a3b57ade" FOREIGN KEY ("rewardBadgeId") REFERENCES "badge"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_missions" ADD CONSTRAINT "FK_cedb05f0e3f7fc3c5cad9ceca00" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_missions" ADD CONSTRAINT "FK_d91466f651650ed5ca0423027cb" FOREIGN KEY ("missionId") REFERENCES "missions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_level" ADD CONSTRAINT "FK_d5fd95368e5ce39ff4baa96446a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badges" ADD CONSTRAINT "FK_7043fd1cb64ec3f5ebdb878966c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badges" ADD CONSTRAINT "FK_bd34ef334baea6f589a53438a1e" FOREIGN KEY ("badgeId") REFERENCES "badge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentor_specializations" ADD CONSTRAINT "FK_60572153397ffbeb32e22c208dc" FOREIGN KEY ("mentorId") REFERENCES "mentors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentorship_relations" ADD CONSTRAINT "FK_f6f7e4fd6532e07c3823b8d7ad0" FOREIGN KEY ("mentorId") REFERENCES "mentors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collaboration_rewards" ADD CONSTRAINT "FK_80cb295d4e4e8a0feb787d0846c" FOREIGN KEY ("specialBadgeId") REFERENCES "badge"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievement_progress" ADD CONSTRAINT "FK_93f082fa43fdce4811582a4e3cd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "achievement_progress" ADD CONSTRAINT "FK_20adca3c4217744bfd8a485e98d" FOREIGN KEY ("achievementId") REFERENCES "cultural_achievements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content" ADD CONSTRAINT "FK_4c43663c2413a8d082b89e8f93c" FOREIGN KEY ("unity_id") REFERENCES "unities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content" ADD CONSTRAINT "FK_34085574fe617e795306890ac60" FOREIGN KEY ("topic_id") REFERENCES "topics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_versions" ADD CONSTRAINT "FK_5ae2351d1653cc9e0daf0ca84ee" FOREIGN KEY ("contentId") REFERENCES "content"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_0dde7fb1a721e8d6a1fbacf1f35" FOREIGN KEY ("versionId") REFERENCES "content_versions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81" FOREIGN KEY ("parentId") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_5a2cfe6f705df945b20c1b22c71" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gamification_achievements_achievements" ADD CONSTRAINT "FK_ea46f6118e982baae585fa28a61" FOREIGN KEY ("gamificationId") REFERENCES "gamification"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "gamification_achievements_achievements" ADD CONSTRAINT "FK_dac3e2f218b828cfeabc4b274b3" FOREIGN KEY ("achievementsId") REFERENCES "achievements"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "gamification_badges_badge" ADD CONSTRAINT "FK_bb9fb4bce626c7391ee29e4afa2" FOREIGN KEY ("gamificationId") REFERENCES "gamification"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "gamification_badges_badge" ADD CONSTRAINT "FK_60a494139c28edaff1797ad1b53" FOREIGN KEY ("badgeId") REFERENCES "badge"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "gamification_active_missions_missions" ADD CONSTRAINT "FK_5c868524a6ca0aff77eb58c3aea" FOREIGN KEY ("gamificationId") REFERENCES "gamification"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "gamification_active_missions_missions" ADD CONSTRAINT "FK_bf067ab5b71aafeb41c8aa81d96" FOREIGN KEY ("missionsId") REFERENCES "missions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content_multimedia" ADD CONSTRAINT "FK_bc7887b608f489d149b88549a8c" FOREIGN KEY ("content_id") REFERENCES "content"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content_multimedia" ADD CONSTRAINT "FK_bb81782a60801a96a1b97da9301" FOREIGN KEY ("multimedia_id") REFERENCES "multimedia"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "content_multimedia" DROP CONSTRAINT "FK_bb81782a60801a96a1b97da9301"`);
        await queryRunner.query(`ALTER TABLE "content_multimedia" DROP CONSTRAINT "FK_bc7887b608f489d149b88549a8c"`);
        await queryRunner.query(`ALTER TABLE "gamification_active_missions_missions" DROP CONSTRAINT "FK_bf067ab5b71aafeb41c8aa81d96"`);
        await queryRunner.query(`ALTER TABLE "gamification_active_missions_missions" DROP CONSTRAINT "FK_5c868524a6ca0aff77eb58c3aea"`);
        await queryRunner.query(`ALTER TABLE "gamification_badges_badge" DROP CONSTRAINT "FK_60a494139c28edaff1797ad1b53"`);
        await queryRunner.query(`ALTER TABLE "gamification_badges_badge" DROP CONSTRAINT "FK_bb9fb4bce626c7391ee29e4afa2"`);
        await queryRunner.query(`ALTER TABLE "gamification_achievements_achievements" DROP CONSTRAINT "FK_dac3e2f218b828cfeabc4b274b3"`);
        await queryRunner.query(`ALTER TABLE "gamification_achievements_achievements" DROP CONSTRAINT "FK_ea46f6118e982baae585fa28a61"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_5a2cfe6f705df945b20c1b22c71"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_0dde7fb1a721e8d6a1fbacf1f35"`);
        await queryRunner.query(`ALTER TABLE "content_versions" DROP CONSTRAINT "FK_5ae2351d1653cc9e0daf0ca84ee"`);
        await queryRunner.query(`ALTER TABLE "content" DROP CONSTRAINT "FK_34085574fe617e795306890ac60"`);
        await queryRunner.query(`ALTER TABLE "content" DROP CONSTRAINT "FK_4c43663c2413a8d082b89e8f93c"`);
        await queryRunner.query(`ALTER TABLE "achievement_progress" DROP CONSTRAINT "FK_20adca3c4217744bfd8a485e98d"`);
        await queryRunner.query(`ALTER TABLE "achievement_progress" DROP CONSTRAINT "FK_93f082fa43fdce4811582a4e3cd"`);
        await queryRunner.query(`ALTER TABLE "collaboration_rewards" DROP CONSTRAINT "FK_80cb295d4e4e8a0feb787d0846c"`);
        await queryRunner.query(`ALTER TABLE "mentorship_relations" DROP CONSTRAINT "FK_f6f7e4fd6532e07c3823b8d7ad0"`);
        await queryRunner.query(`ALTER TABLE "mentor_specializations" DROP CONSTRAINT "FK_60572153397ffbeb32e22c208dc"`);
        await queryRunner.query(`ALTER TABLE "user_badges" DROP CONSTRAINT "FK_bd34ef334baea6f589a53438a1e"`);
        await queryRunner.query(`ALTER TABLE "user_badges" DROP CONSTRAINT "FK_7043fd1cb64ec3f5ebdb878966c"`);
        await queryRunner.query(`ALTER TABLE "user_level" DROP CONSTRAINT "FK_d5fd95368e5ce39ff4baa96446a"`);
        await queryRunner.query(`ALTER TABLE "user_missions" DROP CONSTRAINT "FK_d91466f651650ed5ca0423027cb"`);
        await queryRunner.query(`ALTER TABLE "user_missions" DROP CONSTRAINT "FK_cedb05f0e3f7fc3c5cad9ceca00"`);
        await queryRunner.query(`ALTER TABLE "missions" DROP CONSTRAINT "FK_5debe2687492eacccc1a3b57ade"`);
        await queryRunner.query(`ALTER TABLE "missions" DROP CONSTRAINT "FK_e6378fac08e39332e726de694dd"`);
        await queryRunner.query(`ALTER TABLE "special_events" DROP CONSTRAINT "FK_465c2111241435bcd1706474e38"`);
        await queryRunner.query(`ALTER TABLE "gamification" DROP CONSTRAINT "FK_0ab5141fb59488a7f83cf347fed"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "tags" DROP CONSTRAINT "FK_9f9590cc11561f1f48ff034ef99"`);
        await queryRunner.query(`ALTER TABLE "vocabulary" DROP CONSTRAINT "FK_5a3aa0bd439dc502c591a53b591"`);
        await queryRunner.query(`ALTER TABLE "statistics" DROP CONSTRAINT "FK_c9989a8e8506743633ba5e0aed0"`);
        await queryRunner.query(`ALTER TABLE "progress" DROP CONSTRAINT "FK_36b66733d026a365fb6e6dd63ae"`);
        await queryRunner.query(`ALTER TABLE "progress" DROP CONSTRAINT "FK_0366c96237f98ea1c8ba6e1ec35"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_98668b9e9d6495aef985bf0ba33"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_c7a7b90ae6ce91a6d8bcf09b8b6"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_947b3be6e0895a3a12ad355ab16"`);
        await queryRunner.query(`ALTER TABLE "lesson" DROP CONSTRAINT "FK_f52253c85fe9f56320420603d01"`);
        await queryRunner.query(`ALTER TABLE "unities" DROP CONSTRAINT "FK_a34b5225d21eb0609ff7ee71f68"`);
        await queryRunner.query(`ALTER TABLE "unities" DROP CONSTRAINT "FK_3febc6c71f0413485f16cbd1c9b"`);
        await queryRunner.query(`ALTER TABLE "topics" DROP CONSTRAINT "FK_5d52d2f497534a9e39820d2d817"`);
        await queryRunner.query(`ALTER TABLE "multimedia" DROP CONSTRAINT "FK_be02075eb7a71c44dfc3dbe5651"`);
        await queryRunner.query(`ALTER TABLE "user_rewards" DROP CONSTRAINT "FK_d2904b4fa623c996161687e47d1"`);
        await queryRunner.query(`ALTER TABLE "user_rewards" DROP CONSTRAINT "FK_d538de4678c82491e5a8a8a5834"`);
        await queryRunner.query(`ALTER TABLE "user_achievements" DROP CONSTRAINT "FK_6a5a5816f54d0044ba5f3dc2b74"`);
        await queryRunner.query(`ALTER TABLE "user_achievements" DROP CONSTRAINT "FK_3ac6bc9da3e8a56f3f7082012dd"`);
        await queryRunner.query(`ALTER TABLE "achievements" DROP CONSTRAINT "FK_75e5dd5e08a7ae1f1b24332ef12"`);
        await queryRunner.query(`ALTER TABLE "leaderboards" DROP CONSTRAINT "FK_0b345cd9c25536011d892d0939c"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_3aa23c0a6d107393e8b40e3e2a6"`);
        await queryRunner.query(`ALTER TABLE "activity" DROP CONSTRAINT "FK_3571467bcbe021f66e2bdce96ea"`);
        await queryRunner.query(`ALTER TABLE "evaluation" DROP CONSTRAINT "FK_df167b6625e01d4e26b08b02ba2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb81782a60801a96a1b97da930"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc7887b608f489d149b88549a8"`);
        await queryRunner.query(`DROP TABLE "content_multimedia"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf067ab5b71aafeb41c8aa81d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c868524a6ca0aff77eb58c3ae"`);
        await queryRunner.query(`DROP TABLE "gamification_active_missions_missions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60a494139c28edaff1797ad1b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb9fb4bce626c7391ee29e4afa"`);
        await queryRunner.query(`DROP TABLE "gamification_badges_badge"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dac3e2f218b828cfeabc4b274b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea46f6118e982baae585fa28a6"`);
        await queryRunner.query(`DROP TABLE "gamification_achievements_achievements"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TABLE "content_validation"`);
        await queryRunner.query(`DROP TYPE "public"."content_validation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."content_validation_contenttype_enum"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "content_versions"`);
        await queryRunner.query(`DROP TYPE "public"."content_versions_changetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."content_versions_status_enum"`);
        await queryRunner.query(`DROP TABLE "content"`);
        await queryRunner.query(`DROP TABLE "achievement_progress"`);
        await queryRunner.query(`DROP TABLE "collaboration_rewards"`);
        await queryRunner.query(`DROP TYPE "public"."collaboration_rewards_type_enum"`);
        await queryRunner.query(`DROP TABLE "cultural_achievements"`);
        await queryRunner.query(`DROP TYPE "public"."cultural_achievements_tier_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cultural_achievements_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cultural_achievements_category_enum"`);
        await queryRunner.query(`DROP TABLE "mission_templates"`);
        await queryRunner.query(`DROP TYPE "public"."mission_templates_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."mission_templates_type_enum"`);
        await queryRunner.query(`DROP TABLE "mentorship_relations"`);
        await queryRunner.query(`DROP TYPE "public"."mentorship_relations_type_enum"`);
        await queryRunner.query(`DROP TABLE "mentor_specializations"`);
        await queryRunner.query(`DROP TABLE "mentors"`);
        await queryRunner.query(`DROP TYPE "public"."mentors_level_enum"`);
        await queryRunner.query(`DROP TABLE "streaks"`);
        await queryRunner.query(`DROP TABLE "user_badges"`);
        await queryRunner.query(`DROP TABLE "user_level"`);
        await queryRunner.query(`DROP TABLE "user_missions"`);
        await queryRunner.query(`DROP TABLE "missions"`);
        await queryRunner.query(`DROP TYPE "public"."missions_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."missions_type_enum"`);
        await queryRunner.query(`DROP TABLE "season"`);
        await queryRunner.query(`DROP TYPE "public"."season_type_enum"`);
        await queryRunner.query(`DROP TABLE "special_events"`);
        await queryRunner.query(`DROP TYPE "public"."special_events_type_enum"`);
        await queryRunner.query(`DROP TABLE "gamification"`);
        await queryRunner.query(`DROP TABLE "rewards"`);
        await queryRunner.query(`DROP TYPE "public"."rewards_trigger_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rewards_type_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TYPE "public"."tags_color_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tags_type_enum"`);
        await queryRunner.query(`DROP TABLE "vocabulary"`);
        await queryRunner.query(`DROP TABLE "webhook_subscriptions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "statistics"`);
        await queryRunner.query(`DROP TABLE "progress"`);
        await queryRunner.query(`DROP TABLE "exercises"`);
        await queryRunner.query(`DROP TABLE "lesson"`);
        await queryRunner.query(`DROP TABLE "unities"`);
        await queryRunner.query(`DROP TABLE "module"`);
        await queryRunner.query(`DROP TABLE "topics"`);
        await queryRunner.query(`DROP TABLE "multimedia"`);
        await queryRunner.query(`DROP TABLE "user_rewards"`);
        await queryRunner.query(`DROP TABLE "reward"`);
        await queryRunner.query(`DROP TYPE "public"."reward_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_achievements"`);
        await queryRunner.query(`DROP TYPE "public"."user_achievements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_achievements_achievementtype_enum"`);
        await queryRunner.query(`DROP TABLE "achievements"`);
        await queryRunner.query(`DROP TABLE "badge"`);
        await queryRunner.query(`DROP TABLE "base_achievement"`);
        await queryRunner.query(`DROP TABLE "leaderboards"`);
        await queryRunner.query(`DROP TYPE "public"."leaderboards_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leaderboards_type_enum"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TABLE "activity"`);
        await queryRunner.query(`DROP TYPE "public"."activity_difficulty_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_type_enum"`);
        await queryRunner.query(`DROP TABLE "revoked_token"`);
        await queryRunner.query(`DROP TABLE "evaluation"`);
        await queryRunner.query(`DROP TABLE "cultural_content"`);
    }

}
